name: Code Quality - Pylint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pandas openpyxl

      - name: Run Pylint
        run: |
          echo "Running pylint for all Python files in the repo..."
          pylint $(git ls-files '*.py') --exit-zero --output-format=colorized

      - name: Upload lint report (optional)
        if: always()
        run: |
          pylint $(git ls-files '*.py') --output-format=parseable > pylint-report.txt || true
          echo "Pylint report saved to pylint-report.txt"
